"""
Cross-Metal Regime constant definitions and documentation.
"""

GOLD_STRONG_STEEL_WEAK = "GOLD_STRONG_STEEL_WEAK"
STEEL_STRONG_GOLD_WEAK = "STEEL_STRONG_GOLD_WEAK"
BOTH_STRONG = "BOTH_STRONG"
BOTH_WEAK = "BOTH_WEAK"
MIXED_OR_UNCERTAIN = "MIXED_OR_UNCERTAIN"

ALL_REGIMES = (
    GOLD_STRONG_STEEL_WEAK,
    STEEL_STRONG_GOLD_WEAK,
    BOTH_STRONG,
    BOTH_WEAK,
    MIXED_OR_UNCERTAIN
)
